### ISSUE TITLE
Mergen

### ISSUE THREAD

**Issue by xi-wa** [nezrinstyles/Gruppe-4#8]
Ich glaub wir können die branches nicht automatisch mergen, wenn einige ihre Code direkt in die main branch schreiben und andere in den (a)+(b) branch
Es ist auch meiner Meinung nach einfacher die Codes zu bewerten/kommentieren, wenn man ein Branch erstellt und ein Pull Request macht bevor wir alles in die main branch packen

**Comment by nezrinstyles** [comment]
Ich stimme dirvollkommen zu und habe eine Pull-Request für unsere 3. Aufgabe erstellt, aber leider hat niemand etwas hinzugefügt oder was kommentiert und ich habe die geschlossen

**Comment by nezrinstyles** [comment]
Wenn du willst ich mache es nochmal auf

**Comment by xi-wa** [comment]
Wir sollten am Besten noch auf die anderen warten

**Comment by nezrinstyles** [comment]
Wenn wir alles über einen Pull-Request machen wollen, müssen wir die Datei, die bereits in der main Branche vorhanden ist, löschen, da dies zu einem Konflikt führt und wir nicht completely mergen können

**Comment by xi-wa** [comment]
Ja stimmt, werden wir dann alles über den (a)+(b) branch machen?

**Comment by nezrinstyles** [comment]
Ich glaube ja
